name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        rust: [stable]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Setup Rust
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: ${{ matrix.rust }}
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup MUSL
        if: matrix.os == 'ubuntu-latest'
        run: |
          rustup target add x86_64-unknown-linux-musl
          sudo apt-get -qq install musl-tools
      - name: Build for linux
        if: matrix.os == 'ubuntu-latest'
        run: make release_lnx
      - name: Build for macOS
        if: matrix.os == 'macOS-latest'
        run: make release_mac
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: '*.zip'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Dispatch homebrew Repo update
        run: |
          VERSION = $(patsubst "%",%, $(word 3, $(shell grep version Cargo.toml)))
          $ curl -vv \
            -H "Authorization: token ${{ secrets.HOMEBREW_REPO_GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.everest-preview+json" \
            "https://api.github.com/repos/QWYNG/homebrew-harvest/dispatches" \
            -d '{"event_type": "build", "client_payload": {"version": ${{ github.ref }}'
