name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        rust: [stable]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Setup Rust
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: ${{ matrix.rust }}
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup MUSL
        if: matrix.os == 'ubuntu-latest'
        run: |
          rustup target add x86_64-unknown-linux-musl
          sudo apt-get -qq install musl-tools
      - name: Build for linux
        if: matrix.os == 'ubuntu-latest'
        run: make release_lnx
      - name: Build for macOS
        if: matrix.os == 'macOS-latest'
        run: make release_mac
      - name: Release
        id: release
        uses: softprops/action-gh-release@v1
        with:
          files: '*.tar.gz'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Set version
        id: set_version
        run: echo ::set-output name=version::${GITHUB_REF/refs\/tags\//}
        env:
          GITHUB_REF:  ${{ github.ref }}
      - name: set SHA256
        id: sha_256
        run: |
          wget https://github.com/QWYNG/harvest/releases/download/$VERSION/harvest-$VERSION-x86_64-mac.tar.gz -O mac_release.tar.gz
          echo "::set-output name=sha::$(shasum -a 256 mac_release.tar.gz |awk '{print $1}')"
        env:
          VERSION: ${{ steps.set_version.outputs.version }}
      - name: Dispatch homebrew Repo update
        if: matrix.os == 'macOS-latest'
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.HOMEBREW_REPO_GITHUB_TOKEN }}
          repository: QWYNG/homebrew-harvest
          event-type: update
          client-payload: '{"version": "${{ steps.set_version.outputs.version }}", "sha": "${{ steps.sha_256.outputs.sha }}" }'
