name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        rust: [stable]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Setup Rust
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: ${{ matrix.rust }}
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup MUSL
        if: matrix.os == 'ubuntu-latest'
        run: |
          rustup target add x86_64-unknown-linux-musl
          sudo apt-get -qq install musl-tools
      - name: Set version
        id: set_version
        run: echo ::set-output name=version::${GITHUB_REF/refs\/tags\//}
        env:
          GITHUB_REF:  ${{ github.ref }}
      - name: Build for linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          cargo build --release --target=x86_64-unknown-linux-musl
          zip -j harvest-${VERSION}-x86_64-lnx.zip target/x86_64-unknown-linux-musl/release/harvest
        env:
          VERSION: ${{ steps.set_version.outputs.version }}
      - name: Build for macOS
        if: matrix.os == 'macOS-latest'
        run: |
          cargo build --release --target=x86_64-apple-darwin
          zip -j harvest-${VERSION}-x86_64-mac.zip target/x86_64-apple-darwin/release/harvest
        env:
          VERSION: ${{ steps.set_version.outputs.version }}
      - name: Set SHA256
        if: matrix.os == 'macOS-latest'
        id: sha_256
        run: |
          echo "::set-output name=sha::$(shasum -a 256 harvest-${VERSION}-x86_64-mac.zip |awk '{print $1}')"
        env:
          VERSION: ${{ steps.set_version.outputs.version }}
      - name: Release
        id: release
        uses: softprops/action-gh-release@v1
        with:
          files: '*.zip'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Dispatch homebrew Repo update
        if: matrix.os == 'macOS-latest'
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.HOMEBREW_REPO_GITHUB_TOKEN }}
          repository: QWYNG/homebrew-harvest
          event-type: update
          client-payload: '{"version": "${{ steps.set_version.outputs.version }}", "sha": "${{ steps.sha_256.outputs.sha }}" }'
